name: Cleanup Sessions

on:
    schedule:
        # Run every day at midnight UTC
        - cron: '0 0 * * *'
    workflow_dispatch: # Allow manual triggering

jobs:
    cleanup:
        runs-on: ubuntu-latest
        steps:
            - name: Cleanup old sessions
              run: |
                  curl -X POST \
                    -H "Authorization: Bearer ${{ secrets.CLEANUP_API_KEY }}" \
                    ${{ secrets.CLEANUP_API_URL }}
